---
 - name: enable epel repo for Ansible
   command: yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

###############~~~~DOCKER_CONFIG~~~~###############
 
 - name: Install_Dep_For_Docker
   yum: name={{ item }}
   with_items:
    - yum-utils 
    - device-mapper-persistent-data
    - lvm2
   become: yes

 - name: Add Docker Repo in RHEL/CentOS
   get_url:
     url: https://download.docker.com/linux/centos/docker-ce.repo
     dest: /etc/yum.repos.d/docer-ce.repo
   become: yes

 - name: Install Contaier-selinux
   command: yum install http://vault.centos.org/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm -y

# - name: Enable Docker Edge repo
#   ini_file:
#     dest: /etc/yum.repos.d/docer-ce.repo
#     section: 'docker-ce-edge'
#     option: enabled
#     value: 0
#   become: yes

# - name: Enable Docker Test repo
#   ini_file:
#    dest: /etc/yum.repos.d/docer-ce.repo
#     section: 'docker-ce-test'
#      option: enabled
#      value: 0
#   become: yes

########~~~JENKINS_CONF~~~########

 - name: Download Jenkins repo for Rhel/Centos
   get_url:
    url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0440

 - name: Import GPG Key for Jenking Repo
   rpm_key:
    state: present
    key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key

 - name: Install Dependency for Jenkins
   yum:
    name: java-1.8.0-openjdk
    state: present

########~~~MY_SQL~~~########
 - name: download mysql repo
   get_url: url=https://repo.mysql.com/mysql57-community-release-el7-11.noarch.rpm dest=/tmp/mysql7.11.rpm
   tags: mysql

 - name: install mysql repo
   shell: /bin/rpm -Uvh /tmp/mysql7.11.rpm
   register: mysql_repo_result
   failed_when: "'conflict' in mysql_repo_result.stderr"
   tags: mysql


########~~~MY_SQL~~~########
