---
# Install Tools Packages

- name: Install Grafana repository
  template:
    src:   Grafana.repo.j2
    dest:  /etc/yum.repos.d/grafana.repo
    owner: root
    group: root
    mode:  0644
  when:    ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' 

- name: Install Tools
  package: name={{ item }} state={{ pkgs_state }} update_cache=yes
  with_items: "{{ pkgs_list }}"
