---
 - name: enable docker
   service:
     name: docker
     state: started
     enabled: yes
   become: yes

 - name: enable Jenkins
   service:
     name: jenkins
     state: started
     enabled: yes
   become: yes
